### ISSUE TITLE
Support headers

### ISSUE THREAD

**Issue by fimkap** [Imaginea/react-native-markdown-formatter#1]
Hi. I see that markdown headers #, ## etc. not supported by default. Can it be implemented with regex? Thanks

**Comment by BalajiR** [comment]
Hi @fimkap ,
I'm not sure but might be possible with the existing way of adding custom configs where you can pass own regex pattern and its respective style.

**Comment by regar007** [comment]
@fimkap Hi. I have added custom header with existing custom regex. check out the examples in demo.  Please go through readme.
