### ISSUE TITLE
Default styles are not working

### ISSUE THREAD

**Issue by MuhammadMattiullah** [Imaginea/react-native-markdown-formatter#2]
``` 
      <RNMarkdownFormatter
        defaultStyles={[
          {
            type: 'italic',
            styles: [
            { 
              color:'red',
              fontSize: 24,
            }
            ],
            pattern: ['-'],
            patternType: 'symmetric',
            groups:1,
        }
        ]} // or textBlockComputedStyle
        numberOfLines={100} // 1(no wrap text) or 0(wrap text)
        text={linked}
        regexArray={[]} // or customMarkdownFormatterRegex
      />
```
I am trying to pass the custom styles but its not working ..? Also is it possible to override link onPress function ?
@regar007 please guide

**Comment by hrishiakhade** [comment]
defaultStyles={[styles.textStyle]} 

try like this or 

defaultStyles={[{
                                            fontSize: 14,
                                            fontFamily: 'SoleilW01-Regular',
                                            color: colors.COLOR_231E20
                                        }]}

**Comment by regar007** [comment]
Hi @MuhammadMattiullah , As @hrishiakhade mentioned, you need to pass style object, not pattern itself in default styles.
