### ISSUE TITLE
Italic style cutting the numbers

### ISSUE THREAD

**Issue by hrishiakhade** [Imaginea/react-native-markdown-formatter#3]
When we use the italic style on numbers , and that number is the last character of that word , then its getting cut .. any solution ?  
 I have given minWidth to the parent view of the text.

**Comment by regar007** [comment]
Can you put the string you have tried. and what you expected and results?

I have tried "This is a _12871238_ text". This is working.

**Comment by hrishiakhade** [comment]
In my case, the last 8 is getting cut. I fixed this problem by adding space between Text.

changed from
<Text>{string}</Text>
to
<Text> {string} </Text>
