### ISSUE TITLE
numberOfLines it's not working..

### ISSUE THREAD

**Issue by BogdanRad** [Imaginea/react-native-markdown-formatter#5]
I have seted numberOfLines = 3 but it's not working. I want to add `read more` on text when the text is long...
Here is my code:

 const onLayoutText = event => {
    const { height } = event.nativeEvent.layout;
    if (height >= 51) {
      setShowReadMoreText(true);
    }
  };

  return (
    <>
      <View onLayout={isNewsSingle ? null : onLayoutText}>
        <RNMarkdownFormatter
          defaultStyles={[]} // or textBlockComputedStyle
          text={content}
          numberOfLines={isNewsSingle ? null : 3}
          regexArray={[]} // or customMarkdownFormatterRegex
        />
      </View>

      {showReadMoreText && <Text style={style.readMoreText}>Read more</Text>}
    </>
  );

![image](https://user-images.githubusercontent.com/40359109/84188058-a39f4b80-aa9b-11ea-9b0c-607866dc324b.png)

**Comment by BogdanRad** [comment]
@regar007 can you help me with a solution for this problem, please?

**Comment by BogdanRad** [comment]
@regar007, I think numberOfLines it never worked because jsxArray is an array with text.. and numberOfLines is set on each Text... not on all Text.
![image](https://user-images.githubusercontent.com/40359109/84237768-9a959500-ab02-11ea-8afd-058c53fe0b2f.png)

**Comment by regar007** [comment]
Hi @BogdanRad , You are right about last comment. numberOfLines works for one text block alone. Let me check on it and get back to you.

**Comment by BogdanRad** [comment]
@regar007 thank you very much!

**Comment by BogdanRad** [comment]
@regar007 do you have any update with this problem?

**Comment by regar007** [comment]
@BogdanRad  I have have added numberOfLines support for all the Text. I am guessing you are trying to show 3 lines for individual list items. So it would work for it.

**Comment by BogdanRad** [comment]
ok, thank you @regar007

**Comment by BogdanRad** [comment]
@regar007 I want to change the structure for url... For my task I must to show the link for url without your structure with [name](link) and I want to check all methods for url, eg: google.com, bit.ly/edwq2, https://www.google.com/dsadwqd21).  Can you help me with that, please?
